### ISSUE TITLE
Terragrunt Install Fails 404

### ISSUE THREAD

**Issue by bankershours** [jabba2324/terragrunt-azure-dev-ops#3]
Azure Pipelines Fails:

stages :
  - stage: terragrunt
    jobs:
    - job: terragrunt
      continueOnError: false
      steps:
      - task: installTerragrunt@0
        inputs:
          terragruntversion: 'latest' << tried both
          terragruntversion: '0.18.4'

```
View raw log
Starting: installTerragrunt
==============================================================================
Task         : Install Terragrunt
Description  : Installs terragrunt, currently only for windows
Version      : 0.1.0
Author       : Big Avocado
Help         : https://github.com/gruntwork-io/terragrunt
==============================================================================
Downloading: https://github.com/gruntwork-io/terragrunt/releases/download/v0.18.4/terragrunt_linux_amd64.exe
##[error]Unexpected HTTP response: 404
Finishing: installTerragrunt

Starting: installTerragrunt
==============================================================================
Task         : Install Terragrunt
Description  : Installs terragrunt, currently only for windows
Version      : 0.1.0
Author       : Big Avocado
Help         : https://github.com/gruntwork-io/terragrunt
==============================================================================
Downloading: https://github.com/gruntwork-io/terragrunt/releases/download/vlatest/terragrunt_linux_amd64.exe
##[error]Unexpected HTTP response: 404
Finishing: installTerragrunt

```

**Comment by jonathan-mcewan** [comment]
Hey @bankershours,

A couple of things I can see wrong with what you're trying to do. 

1. Currently this extension only supports windows (as stated in the task description)
2. @jabba2324 hasn't published the Linux change to the marketplace, however, even if he did, it still wouldn't work because the exe needed permissions which weren't added as part of the Linux\MacOS PR

When @jabba2324 can [review my PR](https://github.com/jabba2324/terragrunt-azure-dev-ops/pull/4) this extension should have Linux support

**Comment by esciara** [comment]
Blocked by this too. Would appreciate a quick fix.

In the mean time, is there a workaround ? Can't manage to install it with a `bash` task...
```

**Comment by jonathan-mcewan** [comment]
@esciara, you can create your own private extension with the code [this PR](https://github.com/jabba2324/terragrunt-azure-dev-ops/pull/4) and use that. 

Otherwise, we have to wait for @jabba2324 to approve, merge, create, upload, then publish (the process isn't easy, and this is @jabba2324's project :)

**Comment by didaskein** [comment]
You can also deploy Terragrunt on linux agent using the steps below : 

`
variables:
    - name: TerragruntVersion
      value: "0.35.13"
      readonly: true
    - name: TerraformVersion
      value: "1.0.11"
      readonly: true

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: $(TerraformVersion)

  - task: PowerShell@2
    displayName: "Terragrunt Apply"
    inputs:
      targetType: 'inline'
      script:  |
        $env:ARM_TENANT_ID =  '$(ARM_TENANT_ID)'
        $env:ARM_SUBSCRIPTION_ID =  '$(ARM_SUBSCRIPTION_ID)'
        $env:ARM_CLIENT_ID = '$(ARM_CLIENT_ID)'
        $env:ARM_CLIENT_SECRET =  '$(ARM_CLIENT_SECRET)'

        Write-Host "==>  Az Login with SP"  + $(ARM_CLIENT_ID)
        az login --service-principal -u $env:ARM_SUBSCRIPTION_ID -p $env:ARM_CLIENT_SECRET --tenant $env:ARM_TENANT_ID --output none
        az account set --subscription $env:ARM_SUBSCRIPTION_ID

        # Terragrunt Installation
        $source = 'https://github.com/gruntwork-io/terragrunt/releases/download/v$(TerragruntVersion)/terragrunt_linux_amd64'
        $destination = '$(Pipeline.Workspace)/drop/infra/terragrunt/${{parameters.environment}}/terragrunt'
        Invoke-WebRequest -Uri $source -OutFile $destination
        chmod u+x $destination
        $Env:PATH += ":$(Pipeline.Workspace)/drop/infra/terragrunt/${{parameters.environment}}"

        Write-Host "==> Terragrunt Apply-All on ${{parameters.environment}}"
        cd $(Pipeline.Workspace)/drop/infra/terragrunt/${{parameters.environment}}/
        terragrunt run-all apply --terragrunt-non-interactive -auto-approve
      pwsh: true
      verbosePreference : 'Continue'
      workingDirectory: '$(Pipeline.Workspace)/drop/infra/terragrunt/${{parameters.environment}}/'`

**Comment by jabba2324** [comment]
Apologies for the very late response, this is no longer maintained and I don't have access to the Marketplace page to update any new code here.
